<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Turnos.Api</RootNamespace>
    <UserSecretsId>turnos-api-secrets</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Turnos.Domain\Turnos.Domain.csproj" />
    <ProjectReference Include="..\Turnos.Application\Turnos.Application.csproj" />
    <ProjectReference Include="..\Turnos.Infrastructure\Turnos.Infrastructure.csproj" />
  </ItemGroup>
</Project>
